#!/usr/bin/env bash
mkdir -p ~/.config/nvim/plugin
mkdir -p ~/.config/nvim/after/plugin
mkdir -p ~/.config/nvim/lua/kelvin
mkdir -p ~/.config/nvim/colors

# link wholesale
for f in `find . -regex ".*\.vim$\|.*\.lua$" | sed "s|^\./||"`; do
    echo $f
    rm -rf ~/.config/nvim/$f
    ln -s ~/dotfiles/nvim/$f ~/.config/nvim/$f
done

ln -s ~/dotfiles/nvim/coc-settings.json ~/.config/nvim/coc-settings.json
