#!/bin/sh

/bin/bash -c "sleep 1; /usr/bin/xmodmap $XDG_CONFIG_HOME/x11/xmodmap" # Changes hyper keys.. for caps lock mod key
[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources # Setup xresources
xrandr --dpi 144 --output DisplayPort-0 --mode 3840x2160 --pos 0x0 --primary --rate 60
setbg & # Set wallpaper
redshift & # Screen colour adjustment at night
xset r rate 300 50 & # Increase key speed via rate change
dunst & # Notifications
picom & # Compositor
[ ! -s $XDG_CONFIG_HOME/mpd/pid ] && mpd # Music player daemon
udiskie & # Automounter for removable media
sudo modprobe ddcci & # needed on desktop to get sys/backlight stuff to work with brillo for backlight control
