#!/bin/sh

/bin/bash -c "sleep 1; /usr/bin/xmodmap $XDG_CONFIG_HOME/x11/xmodmap" # Changes hyper keys.. for caps lock mod key
[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources # Setup xresources
xrandr --output DP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI-1 --mode 1920x1080 --pos 1920x0 --rotate normal --output DVI-D-1 --mode 1920x1080 --pos 3840x0 --rotate right # Monitor config
setbg & # Set wallpaper
xset r rate 300 50 & # Increase key speed via rate change
dunst & # Notifications
picom -config & # Compositor
