#!/bin/sh

keyboardsetup & # Increase key repeat speed and remaps caps lock to super key
xrdb $XDG_CONFIG_HOME/x11/xresources & xrdbpid=$! # Setup Xresources
xrandr --dpi 144 --output DisplayPort-0 --mode 3840x2160 --pos 0x0 --primary --rate 60 # For home LG 4k monitor
setbg & # Set wallpaper
redshift & # Screen colour adjustment at night
dunst & # Notifications
picom & # Compositor
[ ! -s $XDG_CONFIG_HOME/mpd/pid ] && mpd # Music player daemon
udiskie & # Automounter for removable media
sudo modprobe ddcci & # needed on desktop to get sys/backlight stuff to work with brillo for backlight control

# Ensure that xrdb has finished running before starting dwm.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
